'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Assignment6.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property downarrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downarrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Godzilla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Godzilla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property King_Kong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("King Kong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uparrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uparrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to King Kong
        '''Godzilla
        '''AL	9	389	5200
        '''AK	3	13241	12328
        '''AZ	10	10190	13148
        '''AR	6	14798	12817
        '''CA	55	9653	1772
        '''CO	9	14247	11867
        '''CT	7	12648	9233
        '''DE	3	10509	5971
        '''DC	3	9698	8586
        '''FL	27	12348	5604
        '''GA	15	7269	14969
        '''HI	4	6355	13118
        '''ID	4	13535	8864
        '''IL	21	19465	14879
        '''IN	11	5236	10822
        '''IA	7	5560	11209
        '''KS	6	9413	10921
        '''KY	8	7336	9910
        '''LA	9	13979	14451
        '''ME	4	10235	12290
        '''MD	10	13977	9612
        '''MA	12	6019	9590
        '''MI	17	9616	5068
        '''MN	10	5668	5972
        '''MS	6	10491	11759
        '''MO	11	13421	12880
        '''MT	3	13396	7723
        '''NE	5	13187	7044
        '''NV	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property voteresults() As String
            Get
                Return ResourceManager.GetString("voteresults", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
