CREATE TABLE [dbo].[1062594333_T_TRANSNET_FACILITY] (
    [FACILITY_ID]         VARCHAR (50) NULL,
    [AIRPORT_CODE]        VARCHAR (50) NULL,
    [AIRPORT_CODE2]       VARCHAR (50) NULL,
    [AMTRAK_STATION_CODE] VARCHAR (50) NULL,
    [FERRY_TERMINAL_CODE] VARCHAR (50) NULL,
    [DATE_UPDATED]        VARCHAR (50) NULL,
    [ADDRESS]             VARCHAR (50) NULL,
    [CITY]                VARCHAR (50) NULL,
    [STATE]               VARCHAR (50) NULL,
    [ZIPCODE]             VARCHAR (50) NULL,
    [METRO_AREA]          VARCHAR (50) NULL,
    [FACILITY_NAME]       VARCHAR (50) NULL,
    [LONGITUDE]           VARCHAR (50) NULL,
    [LATITUDE]            VARCHAR (50) NULL
);

