

# You must have an environment variable defined to the location
# of your g++ for this to work.  For bash shell, change the 
# following line to your g++ path
# export CC=/opt/local2/bin/g++

all:
	g++ -fopenmp -O3  matAverager.cpp -o matavg
