/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package introductory.project;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author Brian
 */
public class InputDialog extends javax.swing.JFrame {
    double amountNumber;
    int checkNumber;
 static InputDialog input = new InputDialog();
 static OutputDialog output = new OutputDialog();

    /**
     * Creates new form InputDialog
     */
    public InputDialog() {
        amountNumber=0.0;
        checkNumber=1000;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JTextField();
        memoField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        memoLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        headerLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        dateDisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameField.setMinimumSize(new java.awt.Dimension(50, 20));

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLabel.setText("Pay To The Order Of:");

        memoLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        memoLabel.setText("Memo:");

        amountLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        amountLabel.setText("$");

        amountField.setToolTipText("Enter Amount..."); // NOI18N

        headerLabel.setText("<html>\n<center>\nLet's Hope This Works \nIndividual Project 1\n</center>\n</html>");

        nextButton.setText("Next>>");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(memoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(memoField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amountField, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLabel)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memoLabel)
                    .addComponent(nextButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMousePressed
        int postDecimalCount=0;
        boolean postDecimal=false;
        boolean itsAllGood=true;
        if(nameField.getText().isEmpty() || memoField.getText().isEmpty() || amountField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please insert a value for each Field.","Improper Input", JOptionPane.ERROR_MESSAGE);
            itsAllGood=false;
        }

        for(int i=0;i<=amountField.getText().length()-1;i++){            
                if(!isNumber(amountField.getText().charAt(i)) && amountField.getText().charAt(i)!='.' ||
                       amountField.getText().charAt(i)=='.' && postDecimal ){
                    i=amountField.getText().length()-1;
                    JOptionPane.showMessageDialog(null, "You may only insert numbers (0-9) and only one decimal (.)", "Improper Input", JOptionPane.ERROR_MESSAGE);
                    amountField.setText("");
                    itsAllGood=false;
                }
                else if(amountField.getText().charAt(i)=='.'){
                    postDecimal=true;
                }
                else if(postDecimal){
                    if(postDecimalCount==2){
                       amountField.setText(amountField.getText().substring(0, i));
                    }
                    postDecimalCount++;
                }
        }
        if(!postDecimal){
           amountField.setText(amountField.getText()+ ".00");
        }
        amountNumber = round(Double.parseDouble(amountField.getText()));
        
       if(itsAllGood){
           
           output.setLabels(nameField.getText(),memoField.getText(), amountField.getText(),input.checkNumber, "");
           input.setVisible(false);
           output.setVisible(true);
           output.doLayout();
       
            if(Continue()){
                input.checkNumber++;
                input.clearDialog();
                input.setVisible(true);
                output.setVisible(false);
            }
       }
    }//GEN-LAST:event_nextButtonMousePressed
    private boolean Continue(){
        int result=0;
        result=JOptionPane.showConfirmDialog(null, "Would you like to make another check?", "Check", JOptionPane.YES_NO_OPTION);
        if(JOptionPane.YES_OPTION==result){
            return true; 
        }
        else{
            output.dispose();
            input.dispose();
        return false;
        }
    }
    private void clearDialog(){
        nameField.setText("");
        memoField.setText("");
        amountField.setText("");
    }
    private boolean isNumber(char ch){
    char test='0';
    while(test<='9'){
        if(ch==test){
        return true;
        }
        test++;
    }
    return false;
}
private double round(double d) {
            DecimalFormat rounded = new DecimalFormat("#.##");
        return Double.valueOf(rounded.format(d));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
                input.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel dateDisplayLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JTextField memoField;
    private javax.swing.JLabel memoLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
