'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TeamAnnex.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ClassroomButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClassroomButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FirstFloor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FirstFloor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FirstFloor_Annex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FirstFloor_Annex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fujinoki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fujinoki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Klein() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Klein", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LabButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LabButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Legend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Legend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LowerLevel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LowerLevel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LowerLevel_Annex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LowerLevel_Annex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property McKenney() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("McKenney", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NextButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NextButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OfficeButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OfficeButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PreviousButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PreviousButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rm1010Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rm1010Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SecondFloor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SecondFloor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SecondFloor_Annex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SecondFloor_Annex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SIUE_Engineering_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SIUE_Engineering_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SIUE_Engineering_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SIUE_Engineering_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ThirdFloor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThirdFloor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ThirdFloor_Annex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThirdFloor_Annex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tornaritis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tornaritis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property White() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("White", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
