'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Project_321._1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property actinium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actinium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aluminium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aluminium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property americium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("americium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property antimony() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("antimony", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property argon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("argon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arsenic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arsenic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property astatine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("astatine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property barium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property berkelium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("berkelium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beryllium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beryllium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bismuth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bismuth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bohrium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bohrium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boron() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boron", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bromine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bromine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cadmium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadmium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property caesium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("caesium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calcium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calcium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property californium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("californium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carbon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carbon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cerium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cerium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chlorine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chlorine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chromium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chromium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cobalt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cobalt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copernicium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copernicium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property curium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("curium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property darmstadtium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("darmstadtium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dubnium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dubnium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dysprosium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dysprosium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property einsteinium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("einsteinium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property erbium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("erbium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property europium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("europium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fermium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fermium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flerovium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flerovium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fluorine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fluorine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property francium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("francium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gadolinium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gadolinium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gallium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gallium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property germanium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("germanium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hafnium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hafnium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hassium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hassium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property helium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("helium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property holmium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("holmium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hydrogen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hydrogen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property indium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iodine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iodine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iridium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iridium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iron() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iron", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property krypton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("krypton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lanthanum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lanthanum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lawrencium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lawrencium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lithium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lithium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property livermorium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("livermorium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lutetium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lutetium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property magnesium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magnesium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manganese() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manganese", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meitnerium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meitnerium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mendelevium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mendelevium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mercury() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mercury", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property molybdenum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("molybdenum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property neodymium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neodymium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property neon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property neptunium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neptunium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nickel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nickel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property niobium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("niobium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nitrogen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nitrogen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nobelium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nobelium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property osmium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("osmium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property oxygen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oxygen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property palladium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("palladium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phosphorus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phosphorus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property platinum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("platinum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plutonium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plutonium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property polonium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("polonium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property potassium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("potassium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property praseodymium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("praseodymium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property promethium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("promethium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property protactinium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("protactinium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property radium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("radium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property radon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("radon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rhenium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rhenium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rhodium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rhodium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property roentgenium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("roentgenium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rubidium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rubidium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ruthenium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ruthenium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rutherfordium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rutherfordium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property samarium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("samarium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scandium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scandium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seaborgium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seaborgium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property selenium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selenium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property silicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property silver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sodium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sodium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property strontium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strontium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sulfur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sulfur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tantalum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tantalum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property technetium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("technetium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tellurium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tellurium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property terbium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("terbium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thallium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thallium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thorium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thorium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thulium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thulium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Thumbs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Thumbs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property tin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property titanium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("titanium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tungsten() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tungsten", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ununoctium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ununoctium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ununpentium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ununpentium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ununseptium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ununseptium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ununtrium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ununtrium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uranium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uranium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vanadium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vanadium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xenon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xenon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ytterbium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ytterbium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yttrium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yttrium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zinc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zinc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zirconium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zirconium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
